[tool.poetry]
name = "work"
version = "0.1.0"
description = "ğŸˆ"
authors = ["KristÃ½na HomolovÃ¡ <kristyna.homolova3@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
flask = "^2.3.2"
scrapy = "^2.9.0"
psycopg2 = "^2.9.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

